# Generated by Django 3.0.4 on 2020-03-21 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
